[System.Serializable]
public enum Moves 
{
   NONE = 0,
   // ARCHER MOVES 
   PIERCE_ATTACK_1 = 1,
   PIERCE_ATTACK_ENEMY,
   BRING_DOWN_FIRE_1,
   BRING_DOWN_FIRE_ENEMY,


   // MAGIC MOVES = 50
   MAGIC_HEAL_SMALL_1 = 50,
   MAGIC_HEAL_SMALL_TEAM,
   MAGIC_HEAL_MID_1,
   MAGIC_HEAL_MID_TEAM,
   MAGIC_HEAL_FULL_1,
   MAGIC_HEAL_FULL_TEAM,
   RESURRECT_SMALL_1,
   RESURRECT_SMALL_TEAM,
   RESURRECT_MID_1,
   RESURRECT_MID_TEAM,
   RESURRECT_FULL_1,
   RESURRECT_FULL_TEAM,
   LIGHTNING_SMALL_1,
   LIGHTNING_SMALL_TEAM,
   LIGHNING_MID_1,
   LIGHNING_MID_TEAM,
   LIGHNING_MAX_1,
   LIGHTNING_MAX_TEAM,

   // MELEE MOVES = 200
   SWIPE_SLASH,
   SWORD_SLASH,
}
