[System.Serializable]
public enum Moves
{
    NONE = 0,
    // ARCHER MOVES 
    PIERCE_ATTACK_1 = 1,


    // MAGIC MOVES = 50
    MAGIC_HEAL_SMALL_1 = 50,
    MAGIC_HEAL_SMALL_TEAM,
    MAGIC_HEAL_MID_1,
    MAGIC_HEAL_MID_TEAM,
    MAGIC_HEAL_FULL_1,
    MAGIC_HEAL_FULL_TEAM,
    RESURRECT_SMALL_1,
    RESURRECT_SMALL_TEAM,
    RESURRECT_MID_1,
    RESURRECT_MID_TEAM,
    RESURRECT_FULL_1,
    RESURRECT_FULL_TEAM,
    LIGHTNING_SMALL_1,
    LIGHTNING_SMALL_ENEMY,
    LIGHNING_MID_1,
    LIGHNING_MID_ENEMY,
    LIGHNING_MAX_1,
    LIGHTNING_MAX_ENEMY,

    // MELEE MOVES = 200
    GUT_SMALL_1  = 200,
    GUT_SMALL_ENEMY,
    GUT_MID_1,
    GUT_MID_ENEMY,
    GUT_HEAVY_1,
    GUT_HEAVY_ENEMY,
    THROB_SMALL_1,
    THROB_SMALL_ENEMY,
    THROB_MID_1,
    THROB_MID_ENEMY,
    THROB_HEAVY_1,
    THROB_HEAVY_ENEMY
}
